---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.451.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: denoland/deno@v2.6.4
- name: mitsuhiko/rye@0.44.0
- name: JohnnyMorganz/StyLua@v2.3.1
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.11.0
- name: LuaLS/lua-language-server@3.16.4
- name: rust-lang/rust-analyzer@2023-11-20
- name: rhysd/actionlint@v1.7.10
- name: google/yamlfmt@v0.21.0
- name: sqls-server/sqls@v0.2.35
